-- Inserción inicial de materiales (PDFs ya subidos al bucket "temario")

insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'ejercicios', 1, 'Ejercicios Tema 1', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/ejercicios/EINDUS-T1-ejercicios.pdf', 'estadistica/ejercicios/EINDUS-T1-ejercicios.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'teoria', 1, 'Tema 1 · Estadística Descriptiva', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/teoria/EINDUS-T1.pdf', 'estadistica/teoria/EINDUS-T1.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'teoria', 2, 'Tema 2 · Probabilidad', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/teoria/EINDUS-T2(1).pdf', 'estadistica/teoria/EINDUS-T2(1).pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'ejercicios', 2, 'Ejercicios Tema 2', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/ejercicios/EINDUS-T2-ejercicios.pdf', 'estadistica/ejercicios/EINDUS-T2-ejercicios.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'ejercicios', 3, 'Ejercicios Tema 3', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/ejercicios/EINDUS-T3-ejercicios.pdf', 'estadistica/ejercicios/EINDUS-T3-ejercicios.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'teoria', 3, 'Tema 3 · Variable Aleatoria', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/teoria/EINDUS-T3.pdf', 'estadistica/teoria/EINDUS-T3.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'ejercicios', 4, 'Ejercicios Tema 4', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/ejercicios/EINDUS-T4-ejercicios.pdf', 'estadistica/ejercicios/EINDUS-T4-ejercicios.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'teoria', 4, 'Tema 4 · Modelos de Probabilidad', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/teoria/EINDUS-T4.pdf', 'estadistica/teoria/EINDUS-T4.pdf') on conflict do nothing;
insert into public.subject_materials (subject_slug, type, tema, title, pdf_url, pdf_storage_path) values ('estadistica', 'teoria', 5, 'Tema 5 · Inferencia Estadística', 'https://lfyymspgcayhxehjmala.supabase.co/storage/v1/object/public/temario/estadistica/teoria/EINDUS-T5.pdf', 'estadistica/teoria/EINDUS-T5.pdf') on conflict do nothing;